title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://33-Hope.github.io/Docs

aux_links:
  Template Repository: https://github.com/33-Hope/Docs
# compress_html:
#   blank_lines: false