title: 人工智能原理2025 spring
description: 人工智能原理2025 spring 课程内容!
theme: just-the-docs

url: https://33-Hope.github.io/Docs

aux_links:
  Template Repository: https://github.com/33-Hope/Docs

  
math: mathjax

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
